### ISSUE TITLE
Detecting Languages

### ISSUE THREAD

**Issue by Shoshin23** [abbyysdk/RTR-SDK.iOS#10]
Hi, 

I understand that ABBYY can read different languages and I've added a few language dictionaries to my app. Something that i've not been able to do is figure out an endpoint in the documentation that returns the language detected.
So when ABBYY encounters french text it would be helpful if it returns the language detected as french and the text. 

If this possible, could you please point me to the endpoint in the documentation? 

Thanks, 
Karthik

**Comment by aaxorb** [comment]
Hi, @Shoshin23 , 
Unfortunately, there is no such functionality.
But you can use native iOS capabilities to determine dominant language of a received result using [ [NSLinguisticTagger dominantLanguageForString:] ](https://developer.apple.com/documentation/foundation/nslinguistictagger/2875117-dominantlanguageforstring?language=objc) method.
