### ISSUE TITLE
IBAN fetching

### ISSUE THREAD

**Issue by Den-Ree** [abbyysdk/RTR-SDK.iOS#12]
Hello! 
We are trying to read Dutch account number, we asked extended licenses for it, but there is only DE, ES, FR, GB. 
Is it possible read it? or we should write our own reg ex? 

For instance, dutch card's format is:
`NL11 ABNA 1111 1111 11`

**Comment by aleksey-ka** [comment]
Hi!

Currently only the countries you have listed are supported, but It is fairly easy to support other countries on our side if you ask for it.

But you can do almost the same thing yourselves through a combination of a regular expression and a **validation function** (see _IFieldBuilder.setOnValidate_). The validation function in this case it to be used to check the checksum of the IBAN

Thank you for your interest in our product!
