### ISSUE TITLE
The operation couldn’t be completed.

### ISSUE THREAD

**Issue by Podiya** [abbyysdk/RTR-SDK.iOS#2]
![screen shot 2016-12-30 at 9 04 35 am](https://cloud.githubusercontent.com/assets/9278751/21559260/0c480634-ce6f-11e6-9870-cf0a8b7d451b.png)
im getting this `The operation couldn’t be completed. (com.abbyy.rtr error 3.)` error when app going to launch :(

**Comment by Juraldinio** [comment]
Sorry for our silence, but we can't reproduce your problem.
If it is still actual, please contact with us by http://rtrsdk.com/contacts/ form.

**Comment by Podiya** [comment]
@Juraldinio  no worries. i figured out that. thanks (Y)
