### ISSUE TITLE
How to recognise MICR_E13B?

### ISSUE THREAD

**Issue by proft** [abbyysdk/RTR-SDK.iOS#23]
Hello! 

**Input:**

1. License file
2. Bank check with MICR_E13B line at the bottom 
3. [ABBYY Mobile Capture SDK](https://www.abbyy.com/mobile-capture-downloads/ios/). Edition 1 - Image & data capture
4. Following snippet in Swift 

``
coreAPI.textRecognitionSettings.setTextTypes(Set([RTRTextType.normal.rawValue, RTRTextType.MICR_E13B.rawValue]))
``

**Output:** It recognizes text + random digits, but *MICR E-13B font is not recognized*.

**Questions:**

1. Do I need any additional features in the License file?
2. Do I need any additional files? Like MRZ.rom, MRZ_EDC.rom
2.1. Where can I get the MRZ_EDC.rom file?

**Comment by KopachevskiiYuriy** [comment]
Hi! You are doing everything right, but this feature is currently not available. We expect the transition to the Developer Preview status at the end of October 2022.
Sorry, we needed to hide these fonts from the API for now.

**Comment by proft** [comment]
Hi!
Thanks for response 

Could you write previous version of SDK where I can use MICR E-13B recognition feature ?

**Comment by KopachevskiiYuriy** [comment]
There is no such version. And it never existed...
Mobile Capture R3 (with this feature) is expected to be released in autumn. Follow the news :)
