### ISSUE TITLE
Invalid recognition language settings. Some languages are unavailable: {(     English )}.

### ISSUE THREAD

**Issue by SharadExt** [abbyysdk/RTR-SDK.iOS#3]
Invalid recognition language settings. Some languages are unavailable: {(
    English
)}.

**Comment by SharadExt** [comment]
I am stuck with this. Why this issue occurs?

**Comment by Juraldinio** [comment]
This issue may occur when the project does not contain the dictionary for the selected recognition language. To fix this problem you just need to include English.edc file in the project.  Go to the section "Build Phases" and create "New Copy File Phase", select destination - "Resources" and subpath - "Dictionaries", add the dictionary file to the list.

**Comment by SharadExt** [comment]
Hi,
Thanks for your answer. Now my project successfully works. Its really good
help for me.

Thanks,
Sharad Patil

**Comment by eul** [comment]
guard let path = Bundle.main.url(forResource:"Dictionaries/English", withExtension: "edc") else {
            return
}

file is exists but I have the same error. And It added to Copy files.

**Comment by ADevelopStudio** [comment]
@eul most likely you don't need it anymore. Just if someone else sees it:
Make sure you add not only "Dictionaries" but "Patterns" as well
<img width="757" alt="screen shot 2019-03-01 at 11 41 38 am" src="https://user-images.githubusercontent.com/5238454/53608514-2ab61080-3c17-11e9-8024-4f0e752c1392.png">
