### ISSUE TITLE
Token timeout

### ISSUE THREAD

**Issue by hoppus** [abbyysdk/RTR-SDK.iOS#4]
I got these errors when i try to init new instance of textCaptureService.

2017-04-18 13:28:17.835174+0300 Set license info
2017-04-18 13:28:17.842886+0300  㥠Ϡ\^A
2017-04-18 13:28:17.850879+0300 Token timeouts: Succeeded timeout not exceeded. No statitistics send.

First instance is initializating without problems, but when i REinit it - deinit, and the init new one, it starts recognizing process just a few seconds  later...
What am i doing wrong? 
Thank you

**Comment by Juraldinio** [comment]
It is only verbose logs, that will help solve issues in non-standard situations.
All critical errors will be fired in onError: delegate method.

**Comment by hoppus** [comment]
@Juraldinio there aren't any error in onError method (

**Comment by aaxorb** [comment]
@hoppus is the problem relevant?
