### ISSUE TITLE
recognise UIImage?

### ISSUE THREAD

**Issue by ADevelopStudio** [abbyysdk/RTR-SDK.iOS#5]
is it possible to use this SDK to recognise text from UIImage?

**Comment by Juraldinio** [comment]
Recognition of UIImage is available in the extended version of RTR SDK library.
For more information, please, contact us: http://rtrsdk.com/contacts/

**Comment by ADevelopStudio** [comment]
Yeah, I've got this SDK as well.. just thinking it would be great to use only one framework in order not to increase app size.. thanks, anyway.
May be manage to convert UIImage to CMSampleBuffer and solve it this way...

**Comment by aaxorb** [comment]
RTR SDK works with both still image and video frames.
Here is sample code for still image recognition:

```
UIImage* image = ...;
NSString* licensePath = ...;
RTREngine* engine = [RTREngine sharedEngineWithLicenseData:[NSData dataWithContentsOfFile:licensePath]];
id<RTRCoreAPI> coreAPI = [engine createCoreAPI];
NSArray<RTRTextBlock*>* result = [coreAPI recognizeTextOnImage:image onProgress:nil onTextOrientationDetected:nil error:nil];
```

> May be manage to convert UIImage to CMSampleBuffer and solve it this way...

You can try it, but remember that `id<RTRRecognitionService>` works with stream of images, but not a single frame. The right way to work with a single image is `id<RTRCoreAPI>`.
