### ISSUE TITLE
Do text recognition only on one image

### ISSUE THREAD

**Issue by Vardan95** [abbyysdk/RTR-SDK.iOS#6]
Hi,

Is there a way to apply real time text recognition only on one image. If for example image was chosen from the gallery.

I tried to create CMSampleBufferRef from UIImage and pass it to RTRTextCaptureService, but nothing happened. (No errors, no callback functions triggered).

Thanks.

**Comment by Juraldinio** [comment]
Sure, here is sample code for image recognition.
```
UIImage* image = ...;
NSString* licensePath = ...;
RTREngine* engine = [RTREngine sharedEngineWithLicenseData:[NSData dataWithContentsOfFile:licensePath]];
id<RTRCoreAPI> coreAPI = [engine createCoreAPI];
NSArray<RTRTextBlock*>* result = [coreAPI recognizeTextOnImage:image onProgress:nil onTextOrientationDetected:nil error:nil];
```
But it require special license. You should contact our [sales department](http://rtrsdk.com/contacts/) to request a free trial. 
If you have any technical issues we will be glad to answer them.

**Comment by Vardan95** [comment]
@Juraldinio In the SDK folder there is a licence file, isn't it enough?

**Comment by Juraldinio** [comment]
Unfortunately no.
License that delivered in the archive, contains permissions only for [TextCapture](http://rtrsdk.com/documentation/ios-api-reference/rtr-engine/create-text-capture-service/) and [CustomDataCapture](http://rtrsdk.com/documentation/ios-api-reference/rtr-engine/create-data-capture-service/) scenarios.
