### ISSUE TITLE
"Some languages are unknown" Error

### ISSUE THREAD

**Issue by eul** [abbyysdk/RTR-SDK.iOS#8]
All steps from tutorial was done but getting the error when try to recognize text:

The English file is present in bundle:
guard let isPresent = Bundle.main.url(forResource:"Dictionaries/English", withExtension: "edc") else {
            return
        }

**Error Domain=com.abbyy.rtr Code=3 "Invalid recognition language settings. Some languages are unknown: {(
    English
)}." UserInfo={NSLocalizedDescription=Invalid recognition language settings. Some languages are unknown: {(
    English
)}.}**

**Comment by eul** [comment]
Please close this task.
The problem was when 
` var engine: RTREngine?`
was a local variable and `RTRTextCaptureService` was global

**Comment by aleksey-ka** [comment]
Glad to here that you've found the cause of the problem.
Thank you for using our product
