### ISSUE TITLE
Works for me only in landscape.

### ISSUE THREAD

**Issue by Shoshin23** [abbyysdk/RTR-SDK.iOS#9]
Hi, 

I've integrated ABBYY's OCR into my app but it seems to work only while the phone is in landscape mode. I've integrated the sdk as mentioned in the docs but it doesnt seem to work still. 

Anything i could be doing wrong? 

Thanks, 
Karthik

**Comment by aaxorb** [comment]
@Shoshin23 what about [RTR samples](https://github.com/abbyysdk/RTR-SDK.iOS), did you examine them? Samples should support all orientations.

May be you missed this code lines:
```
AVCaptureVideoOrientation videoOrientation = [self videoOrientationFromInterfaceOrientation:[UIApplication sharedApplication].statusBarOrientation];

if(connection.videoOrientation != videoOrientation) {
	[connection setVideoOrientation:videoOrientation];
	return;
}
```
from `- (void)captureOutput:didOutputSampleBuffer:fromConnection:` method.

**Comment by Shoshin23** [comment]
Hi @aaxorb,
I pasted the code sample you had provided but now it only works in portrait. I'm missing something here as I'm replicating the samples almost in my case. 

Can you shed some light on how to keep abbyy running even while switching orientations?

Thanks,
Karthik

**Comment by aaxorb** [comment]
@Shoshin23 ,
I can assume, that your applicaton does not support landscape orientation at all and` [UIApplication sharedApplication].statusBarOrientation` always returns `UIInterfaceOrientationPortrait`. If so, you should find the way to determine orientation without `statusBarOrientation` method, or change your code to support multiple orientations.
